color:
  saturation: 0.6913313
  brandStrength: 0.05782039
  rhythmicContrast: 0.686879
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  lightness: 0.5670089
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.7329749
typography_spectrum: 0.1612903
name: 'Contech '
